import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { loadPlaywright, chromiumExecutable } from './playwright-runtime.mjs';
const { chromium } = await loadPlaywright();
const browser = await chromium.launch({ executablePath: chromiumExecutable(), headless: true });
const base = process.env.WORKBENCH_URL ?? 'http://127.0.0.1:5191';
const dir = fileURLToPath(new URL(`./.artifacts/states-${process.env.AUDIT_STAGE ?? 'before'}/`, import.meta.url));
await mkdir(dir, { recursive: true });
const results = [];
const context = await browser.newContext({ viewport: { width: 390, height: 844 } });
const page = await context.newPage();
page.setDefaultTimeout(12000);
const check = async (name, body) => { try { await body(); results.push({ name, pass: true }); } catch (e) { results.push({ name, pass: false, error: e.message }); } console.log(JSON.stringify(results.at(-1))); };
const shot = async name => {
 for (const width of [1440, 390, 320]) for (const theme of ['light', 'dark']) {
  await page.setViewportSize({ width, height: 844 });
  await page.evaluate(async preference => { const { applyTheme } = await import('/src/theme.ts'); applyTheme(preference, false); }, theme);
  await page.waitForTimeout(200);
  await page.screenshot({ path: `${dir}/${name}-${width}-${theme}.png`, fullPage: true });
 }
 await page.setViewportSize({ width: 390, height: 844 });
};
const go = async route => { await page.goto(base + route); await page.locator('h1').waitFor(); await page.waitForTimeout(400); };
const geometry = async () => page.evaluate(() => ({ width: innerWidth, scroll: document.documentElement.scrollWidth }));
await page.goto(base);
await page.locator('.user-choice').first().click();
await page.locator('.who').waitFor({ state: 'attached' });
await check('closed mobile sidebar excludes keyboard focus', async () => {
 await page.locator('.nav-item').first().evaluate(e => e.focus());
 assert.equal(await page.locator('.sidebar').evaluate(e => e.contains(document.activeElement)), false);
});
await check('mobile menu keyboard range, Escape and focus restoration', async () => {
 const trigger = page.locator('.menu-btn');
 await trigger.click();
 await page.locator('.who button.icon-btn').focus();
 await page.keyboard.press('Tab');
 assert.equal(await page.locator('.mobile-close').evaluate(e => e === document.activeElement), true);
 await page.keyboard.press('Escape');
 assert.equal(await trigger.evaluate(e => e === document.activeElement), true);
 assert.equal(await trigger.getAttribute('aria-expanded'), 'false');
});
await check('theme preference light/dark/system and demo admin permission boundary', async () => {
 const select = page.locator('.theme-select select');
 await select.selectOption('dark');
 await page.waitForFunction(() => document.documentElement.dataset.theme === 'dark');
 assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark');
 await page.emulateMedia({ colorScheme: 'light' });
 assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark');
 await select.selectOption('system');
 await page.waitForFunction(() => document.documentElement.dataset.theme === 'light');
 assert.equal(await page.locator('html').getAttribute('data-theme'), 'light');
 await page.emulateMedia({ colorScheme: 'dark' });
 await page.waitForFunction(() => document.documentElement.dataset.theme === 'dark');
 assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark');
 await select.selectOption('light');
 await go('/admin');
 assert.equal(new URL(page.url()).pathname, '/');
});
await check('long job title and URL fit mobile page and details', async () => {
 await page.evaluate(async () => {
  const { post } = await import('/src/api/client.ts');
  await post('/jobs', { title: 'LongJobTitle'.repeat(20), company: 'Company'.repeat(15), location: '广州', sourceUrl: 'https://example.invalid/' + 'path'.repeat(90), deadlineDate: null, jdText: 'LONG_UNBROKEN_JD_'.repeat(60) });
 });
 await go('/jobs');
 await shot('long-job');
 assert.deepEqual(await geometry(), { width: 390, scroll: 390 });
 await page.getByRole('button', { name: '查看 JD 与条件', exact: true }).first().click();
 await page.getByRole('dialog').waitFor();
 await shot('long-job-detail');
 assert.equal(await page.locator('.modal').evaluate(e => e.scrollWidth <= e.clientWidth + 1), true);
 await page.keyboard.press('Escape');
});
await check('private job modal keyboard trap, escape and focus restoration', async () => {
 await go('/jobs');
 const trigger = page.getByRole('button', { name: '添加私人 JD', exact: true });
 await trigger.click();
 const dialog = page.getByRole('dialog');
 await shot('private-job-form');
 await dialog.getByRole('button', { name: '保存岗位' }).focus();
 await page.keyboard.press('Tab');
 assert.equal(await dialog.getByRole('button', { name: '关闭', exact: true }).evaluate(e => e === document.activeElement), true);
 await page.keyboard.press('Escape');
 assert.equal(await trigger.evaluate(e => e === document.activeElement), true);
});
await check('profile validation and loading/error states', async () => {
 await go('/profile');
 await page.getByRole('button', { name: '添加经历', exact: true }).click();
 await page.locator('.form-notice[role=alert]').waitFor();
 await shot('profile-invalid');
 await page.evaluate(async () => { const { demoTransport } = await import('/src/data/index.ts'); demoTransport().controls.setLatency(3000, 0); });
 await page.locator('.nav-item[href="/jobs"]').first().evaluate(e => e.click());
 await page.locator('.inline-loading').first().waitFor();
 assert.equal(await page.locator('.content .empty').count(), 0);
 await shot('jobs-loading');
 await page.waitForTimeout(3300);
 await page.evaluate(async () => { const { demoTransport } = await import('/src/data/index.ts'); demoTransport().controls.setLatency(0, 0); demoTransport().controls.failNextRequests(10, { message: '本地审查模拟服务不可用' }); });
 await page.locator('.nav-item[href="/plan"]').first().evaluate(e => e.click());
 await page.locator('.resource-notice').first().waitFor();
 await shot('plan-error');
 await page.evaluate(async () => { const { demoTransport } = await import('/src/data/index.ts'); demoTransport().controls.failNextRequests(0); });
});
await check('settings pending sync and rejected/conflicting local operation', async () => {
 await page.evaluate(async () => {
  const { get } = await import('/src/api/client.ts');
  const { queueOperation } = await import('/src/offline.ts');
  const session = await get('/session');
  const profile = await get('/profile');
  await queueOperation({ userId: session.user.id, entity: 'profile', entityId: session.user.id, baseVersion: 99999, action: 'upsert', payload: profile });
 });
 await go('/settings');
 await shot('settings-pending');
 await page.getByRole('button', { name: '立即同步', exact: true }).click();
 await page.locator('.conflict-card').waitFor();
 await shot('settings-conflict');
 await page.getByRole('button', { name: '采用服务端版本', exact: true }).first().click();
});
await check('resume parse draft, quote rejection and version conflict dialog', async () => {
 await go('/profile');
 const [chooser] = await Promise.all([page.waitForEvent('filechooser'), page.locator('.upload-box').click()]);
 await chooser.setFiles({ name: '示例简历-林晓.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4 local test fixture') });
 await page.getByRole('button', { name: '上传并解析', exact: true }).click();
 await page.locator('.draft-review').waitFor();
 await shot('resume-draft');
 await page.getByLabel(/经历原文摘录/).fill('不存在于任何经历的引用');
 await page.getByRole('button', { name: '添加引用', exact: true }).click();
 await page.locator('.toast.error').waitFor();
 await shot('quote-error');
 await page.locator('.experience-card').first().getByRole('button', { name: '编辑', exact: true }).click();
 await page.evaluate(async () => {
  const { get, put } = await import('/src/api/client.ts');
  const bundle = await get('/evidence');
  const e = bundle.experiences[0];
  await put(`/evidence/experiences/${e.id}`, { ...e, baseVersion: e.version });
 });
 await page.getByRole('button', { name: '保存经历', exact: true }).click();
 await page.getByRole('dialog', { name: '记录版本已变化' }).waitFor();
 await shot('version-conflict');
 await page.keyboard.press('Escape');
});
await check('populated match, portfolio, plan, rewrite and application states', async () => {
 await go('/match');
 await page.getByLabel('选择岗位').selectOption({ index: 1 });
 await page.getByRole('button', { name: '开始分析', exact: true }).click();
 await page.locator('.score-grid').waitFor();
 await shot('match-populated');
 await page.getByRole('button', { name: '生成组合', exact: true }).click();
 await page.locator('.portfolio-row').first().waitFor();
 await go('/plan');
 await page.getByRole('button', { name: '生成两周计划', exact: true }).click();
 await page.getByRole('button', { name: '确认计划', exact: true }).waitFor();
 await shot('plan-draft');
 await page.getByRole('button', { name: '确认计划', exact: true }).click();
 await page.waitForTimeout(500);
 await page.getByRole('button', { name: '生成改写', exact: true }).first().click();
 await page.locator('.rewrite-item').first().waitFor();
 await shot('plan-rewrite');
 await go('/jobs');
 await page.getByRole('button', { name: '加入投递跟踪', exact: true }).first().click();
 await page.getByText('已加入投递跟踪', { exact: true }).waitFor();
 await go('/applications');
 await page.getByRole('button', { name: '状态历史 / 面试', exact: true }).first().click();
 await shot('application-history');
 assert.deepEqual(await geometry(), { width: 390, scroll: 390 });
});
await check('admin page and both admin modals with browser-only permission fixture', async () => {
 await page.locator('.menu-btn').click();
 await page.locator('.who button.icon-btn').click();
 await page.evaluate(() => { const json = Response.prototype.json; Response.prototype.json = async function () { const b = await json.call(this); if (b?.user?.role === 'admin') b.user.demo = false; return b; }; });
 await page.locator('.user-choice').last().click();
 await page.locator('.nav-item[href="/admin"]').first().evaluate(e => e.click());
 await page.getByRole('heading', { name: '维护公共岗位', exact: true }).waitFor();
 await shot('admin');
 await page.getByRole('button', { name: '新增公共岗位', exact: true }).click();
 await shot('admin-create');
 await page.keyboard.press('Escape');
 await page.getByRole('button', { name: /编辑/ }).first().click();
 await shot('admin-edit');
 await page.keyboard.press('Escape');
});
await context.close();
await browser.close();
await writeFile(`${dir}/results.json`, JSON.stringify(results, null, 2));
process.exitCode = results.some(r => !r.pass) ? 1 : 0;
